### PR TITLE
[FEATURE] Create file and folder structure

### PR DESCRIPTION
**Pull request by cedricziel**
Leverage typo3-console to create the file and folder structure
through composer events.

This also introduces a hash for common scripts which are needed
by the majority of composer-based TYPO3 projects for plumbing scripts that
need to be executed on the to main events that mutate the library state (install && update)

Can also be invoked manually through `composer typo3-cms-scripts`.

Should be merged back into the next 8.7 release of the dist.

### CODE REVIEW

**Comment by bmack** [comment]
I think flushing cache and set up db structure should be added as well, what do you think?

Could we also describe these actions in the README?

**Comment by cedricziel** [comment]
Well.. Yes and no :)

I think we should only automate the actions that do not require a db connection, so that CI environments don't necessarily require a db connection. - Even `composer create-project` would fail if no db connection was available whilst executing the scripts.

Flushing the cache is a good idea, as long as it only handles file caches - the reason is that otherwise no mutating operations with composer would be possible anymore since the `post-update` scripts would fail and the composer transactions would be rolled back.

I think for those, we should define another script such as `typo3-fasten-your-seatbelts` or `typo3-org-is-not-responsible-for-broken-project`.

Jokes aside - there are a bunch of other operations that could be potentially useful such as generating the `PackageStates` from the set of required extensions and running the extension setup for the active extensions, but we should carefully choose which we want. - Symfony has a competitive advantage in the sense that they use `https://packagist.org/packages/incenteev/composer-parameter-handler` to ask the user about missing parameters so they have at least a good chance of having the database credentials available.

--

I think we should start with the directory structure script and then go from there.

**Comment by bmack** [comment]
Agreed :) Let's do separate scripts for "t3-deploy" and "t3-setup" etc.

**Comment by cedricziel** [comment]
Sounds great - thx for the merge!

**Pull request merged**
