### PR TITLE
Update for TYPO3 v12

### PR DESCRIPTION
**Pull request by DavidBruchmann**
remove helhum/typo3-console due to missing compatibility

### CODE REVIEW

**Comment by ohader** [comment]
It's actually a bit more...
* adjust `master` branch, platform reqs
* create branch `12.x`, set versions to `^12.0.0@dev` (see https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/commit/674aae2bc0bdc59d6caacf6a7a96439748bec19b - before switching to LTS 11.5.0 back then)
* create tag `12.0.0`, set versions to `^12.0` (like in this PR)

**Comment by gilbertsoft** [comment]
`typo3/cms-recordlist` must be removed.

**Comment by DavidBruchmann** [comment]
ok, not sure if I could have done all. But thanks for caring and explanation!

**Comment by DavidBruchmann** [comment]
@ohader  Actually I don't understand all steps in detail, so feel free to dump my PR.

**Comment by ohader** [comment]
I think it's easier for me to drop this PR and do the steps manually.

**Comment by ohader** [comment]
Summary:
* change in `main` branch: https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/commit/5bcad0e8ebe5866e9c600ebe8f93210e01dad165
* branch off `main` → new `12.x` with change: https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/commit/06248b0ab0a6e1e9f00c2a2dbf87e467c6ed4bb0
* created tag `v12.0.0` from `12.x` branch: https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/releases/tag/v12.0.0
* change in `12.x` branch: https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/commit/e5ed99f574a27eda67593ee5ddf3b3badd5ad21a

**Comment by ohader** [comment]
Adjusted manually, closing this PR.

**Pull request closed without merging**
